apiVersion: 1

contactPoints:
  - orgId: 1
    name: DevOps Email
    receivers:
      - uid: devops-email
        type: email
        settings:
          addresses: kalpanapramodya97@gmail.com
          singleEmail: false
        disableResolveMessage: false

  - orgId: 1
    name: Critical Email
    receivers:
      - uid: devops-email-critical
        type: email
        settings:
          addresses: kalpanapramodya97@gmail.com
          singleEmail: false
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: DevOps Email
    group_by: ['alertname', 'job']
    routes:
      - receiver: Critical Email
        matchers:
          - severity = critical
        group_wait: 0s
        repeat_interval: 1h
      - receiver: DevOps Email
        matchers:
          - severity = warning
        repeat_interval: 6h
